const contractAddress = "0xE52C1b87F8aFCB994D7000969e87505CFDa44Dd5"; // Replace with your own contract address
const chain = 'polygon'; // goerli, polygon, or ethereum

const welcome_h1 = "Welcome to the Shilly Sheep NFT Project!!";
const welcome_h2 = "Connect to MetaMask to Get Started";
const welcome_p = 'The Shilly Sheep NFT Project is part of Granddads Farm. Follow the steps to Mint your own.';
const h1_presale_coming_soon = "Shilly Sheep NFT Drop Coming Soon!!";
const h1_presale_mint = "Shilly Sheep Pre-Sale Minting Open!!";
const h1_public_mint = "Shilly Sheep Public Minting Open!!";
const h2_presale_coming_soon = "Shilly Sheep Pre-Sale Minting Countdown";
const h2_presale_mint = "Shilly Sheep Public Minting Countdown";
const p_presale_coming_soon = "We are working hard to launch the Shilly Sheep NFT Collection. Stay tuned for updates!";
const p_presale_mint_not_whitelisted = "You are not whitelisted for the pre-sale.. 😢";
const p_presale_mint_whitelisted = "You're on the whitelist for the pre-sale! 🎉";
const p_presale_mint_already_minted = "You've already claimed your whitelist mint. Thank you! 🎉";
const p_public_mint = "No whitelist needed. Public minting of Shilly Sheep is now open! 🎉";
const button_presale_coming_soon = "Get on the Whitelist for out future projects";
const button_presale_mint_whitelisted = "Mint Your Special Shilly Sheep NFT";
const button_presale_mint_not_whitelisted = "Get on the Whitelist";
const button_presale_already_minted = "Join The Granddads Farm Community";
const button_public_mint = "Mint Your Shilly Sheep NFT";
const mint_failed = "Minting failed. 😢 Please try again.";
